### ISSUE TITLE
what formats does this support?

### ISSUE THREAD

**Issue by astronautfa** [mwat56/kaliber#4]
Does this support epub and mobi rendering on the server?

**Comment by mwat56** [comment]
Thanks for asking!
This is merely a web-frontend to a Calibre database, so the rendering has to be done at the user's side anyway.
The server cannot know the device specifics and capabilities of your device. However, most browsers support  various Ebook formats, either natively or with the help of plugins. So there's no real need for the server to read, interpret, convert somehow to HTML, just to deliver that over the network. It would be a waste of electricity, processing time, and bandwidth.
